### ISSUE TITLE
question abount table.1

### ISSUE THREAD

**Issue by yfzhang114** [Yuqifan1117/HalluciDoctor#8]
I recently came across your paper and found it to be quite interesting. I would like to cite your work and compare it with my own research. Specifically, the results in Table 1 caught my attention.

Would you be able to provide some guidance on how to re-implement these results? Any tips or suggestions would be greatly appreciated.

Looking forward to hearing from you.

**Comment by Yuqifan1117** [comment]
Thanks for your interest. The CHAIR metric computes in obj/rel/attri levels and the calculation process is shown in eq. (1,2,3). Specifically, we focus on the mixture of the coco category and the VG category for comprehensive entities. 

Then we abstract entities, relations, and attributes by a textual scene graph parser for evaluation. To extend the ground truth in COCO’s images, we adopt GroundingDINO to annotate objects (box_threshold=0.3, text_threshold=0.25) and use the image-text similarity of BLIP to judge the existence of relations and attributes (threshold <  0.25 denotes there exist hallucinations). 

Due to our busy schedule, we have not sorted out this part of the code recently. Hope to help you!
